### ISSUE TITLE
Unhandled Error Notification

### ISSUE THREAD

**Issue by OptTrader** [cocoascientist/Luna#1]
When i tried to load your demo with my api keys...I get the "Error: Unhandled notification: nil" message. Any idea where the problem is coming from? I updated to Xcode: Version 7.3.1. Not sure if that's the cause.

Great tutorials btw.

**Comment by andyshep** [comment]
The error is probably coming from the location manager. Make sure the app has been granted access to the users location-- this is used to fetch the moon and phase info. I pushed a [commit to master](https://github.com/cocoascientist/Luna/commit/129a3450f79740e2c8071ad6d49d4b96816bbaa9) that improves some of the error reporting.

Thanks a lot for the feedback!
